---
inherit_mode:
  merge:
    - Exclude

Committee:
  Enabled: true

Committee/AssertSchemaConformWithoutRequest:
  Description: Check if `assert_*_schema_conform` is called without making an HTTP request.
  Enabled: pending
  VersionAdded: "<<next>>"

Committee/MultipleSchemaConform:
  Description: Check for multiple schema conformance assertions within the same request block.
  Enabled: pending
  VersionAdded: "<<next>>"

Committee/RedundantResponseStatusAssertions:
  Description: Check for validation of redundant response HTTP status codes.
  Enabled: pending
  VersionAdded: "0.1"

Committee/UnspecifiedExpectedStatus:
  Description: |
    Check if the status code is specified as an argument to the method of the Committee
    where the expected response status code is required.
  Enabled: pending
  VersionAdded: "0.1"
