---
inherit_mode:
  merge:
    - Exclude

Committee:
  Enabled: true

Committee/ExpectedResponseStatusCode:
  Description: |
    Check if the status code is specified as an argument to the method of the Committee
    where the expected response status code is required.
  Enabled: pending
  VersionAdded: "<<next>>"

Committee/RedundantHttpStatus:
  Description: Check for validation of redundant response HTTP status codes.
  Enabled: pending
  VersionAdded: "<<next>>"
